language: java

sudo: false

jdk:
- oraclejdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -B

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.m2"

after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
- chmod +x $GPG_DIR/publish.sh
- "$GPG_DIR/publish.sh"

env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: La72bzH4G3IeH2o9D5q4O33xTpbYYtQhZlEqWnSphiwqKwROpXRumXuhWIvpgGOrTPEJIl9DHavOiXJk9QQU3MUUY+sLn6XZzZEopu8mSWOxS0ZeBCjbJJYsr9TtLu/qNtk6xn+d0Rbm+PcCBbOw6utE4yfd8zgvLeP9Jo189EMdqlAHJzSLursXMPQVKRttn/9Igkqgc/e4K1UKJpO+ZjQFPS+LxWNQiA2gkzbUR05ckBg4DDJrcXEkX5Kqa5+/T4o8mAwr7BrraPuy1DiwC1BnhxBEb+o1VVW1IO8ZX9lsuBP72o741xTzsibqAB65p3clhN6cl+RiFV0gJQY+JdjxP2jGBmT8Yz21tV9gufevJydwxPq233q2866AO0mx0NrCBszEiB+4Agzx4Y0oVd5CovPCTs29ciAwznTQWp/EB5v8UaDuLAwJKM787elgx9d1Loh0bGhpmMNyDk5Eatz4qodfQ9kPX924z3xgpjmo4x34doKNbEdCvaZ2l+Inq+aRMW72mXu36OEfUyZYtQ/OIxlrAO4RxTYoXoBFhoXhxD0lGtCBmcEDOn03IGvN1/3wsm7vq/Pf82s6kwzbUzn6UBGE4EEP4jRXEh210n/1gxnXKFpJgCYOi+2XY6xSbWCS1+j9n3+Cl4g6bsaeI/LQuzIICNVsRSJK36LpvNM=
  - secure: qgWkmeqv7BuLDRm2hrh8hTdW7OVgtezspcnSM94+YJgbNClgMI0j2X8/xn08HabcpJikNgIo3xI8TU3NLWa8qUobrgRQfngvgftrytXK3UC+FiGFyJj6IEcAw3oPwcLHtix4aAJXXJ/HRQ3Gu9lKb4cXgPk7Lsfr+7i1n/V9/gxh3K6YuzfyrL1LoOSDfdk2myYwvYwC2/VJBUAtjmfZ6wrRzF6EczBwBfipvX5oVjEqFQMeR3uyWa6+WAJTilWmU7iF/yax4+dKlKP/gpEljgOzUg5q+OThFDXiped6MnHfeCdrLUyHZNg+BOahREuOUc9+LJiDhANwxYOkR86FoYF43NuePi417GTfwBgoxfZV9H362JnObNq4i0YLYxIQxbAoh3XzF7ubEXHvtk6ClV2yqW/OQ0XKBbfKB+dggw9zwYQ82sNPWFjSA6U6p1WBMuNWA1urv94dQWibKBG8sHtVZTs5X0aK/lRXzEYYvKL4iqcU8g2DzQ7sZZ6PP9zuaOw1Wf/EU5i02MEFg5f6JRUoiUTEBvmWnxlVdMuMtfoCS4OHjems7YnURZzkfVweGOhLRgVKkHMR9dlbXpC733iWPzr02xzifJuuqREZW1ZO0Don8defCLmaDRBLo+ufByk3L6SYJKa62S4MqXwK+SJsgYPVVNWutbrdRgpb1GA=
  - secure: Y7x9EuBJ+iJHl0UJZuXU8oFpSSPj3kc0MN9rshOUNy3p5oZdy/6u72sRQxZqClG3MXD+6w08UbEy0CG8hc56j6w8pai5YGSQaDFMmT+CkjtGzfc1tDOQrCQ7EzN+AsRiOhl/6k93DJ6r/nXlRZRARX5Cc87DwQU+lfgHlF3rzwdoiXrxdlwpP7aycyc7Bkiskb3D40p9T6mHUIQxaT9CbyNFWpfxv/AtiCH2NqSL6OCk+Qhs3JagiWGhZb+dB0pAVBTLD4vbz4FAWYN8RcarDYO9S5Cwpff1PVNGquHw4J9PPRyQfJM6zpexWrd2lVlPWrR/ZDMZ7CF/RtkbbuO01fl1ZC3bCjt2keiosHV0VOrw4q0EaoMtwb/WM7Orb2Qooz3dcHk5hdF7B3m1daMsUlsZmvSL7IXsBMkvnW4PY7sfGsTHVCVOIorzP1roXMULtt9s0MHi23VJBjd7vKgf2U917daVWMrVou9SyTYBLQXBmdqmBSAMaScChhQooUHvpsV4SMWbcopw44yIi0aoVoCmanuNAJQIbOn0UiSInESfz/S1Dnx1KsYTIrIEG9dkXs58nLBVVYEGHvkjj8UtD8s9xNzI74h/0DHzZZtZR8I1YaFhdFNpKEAYaWT8BIG6WL7r9Vq2VUo3X8QvXRAml/rlk/0Bri0nfWRquZWzVOI=
  - secure: i/47U4CkR2xH4/MRoHxMpMbR+Rf730Wr376gkapFeMVohghT0QiUfpgA6lVuBEdBLHujtAojUZx7Tb0McRhKmJpiuswPJZyZW6+HeffFdc8TglcUCmjnHh4riodRC31evr7Pj0L+ERrFz46oFzydOxEurnSM8CGcYP9IJMabGWNdi+utYXAsMgXJAQk7JZ2TYPO5MK8vlqfb++MPEzBgwNksO+/WW3i+1tb7+CynnA/4iILknh4+uEIyEob/N/IDf6WDdroqkUTvrlYddsjlSLhvBL9tMI+ntQEXRcNyoxzrCPc3UlTvOLah+qK6+cofwCYfS2owxV8RgawLOZwjnLEl9n38sdbtPxQnJtQhCa37WI2AtREnGdmfyCXr559wzk+3cSDL/MM0lH8FaGrqvBCYaV/r0359346RKEVQM3kDo4iYCIk5lCyXZy5gtTwvIVHm4+caN1YtS+Ohyu8YNrAKJxyPpoTyvoaOO1qplIVP/vR7KuJo0vEnX38OtzKE+ogmfesQHAcJ3i4t06V9DW6Ar8XhJi21qEvTVlS8gZK520S9/7TAOgsBoCPcfrpFQ5aeHr9yDJhtE9GB95IU/R628iEYAX3rzLrqhJj+HsGr7WgJOJzBxfDa4jwVYdnmqwbEhrm58AcryjGhLleElrFYhMa/cgnjGZ1H1uBDlE4=
  - secure: n9+EIYAy0pT9gj4RxFSWYOR3RhXCy2yYsU5oTee5MhQZeYf4xvIhTwGlTiep3pH7mVoaiyvYMUc4edn2GC59yOaPtQdqKB3B0/B53wFTbobtBKjPa504PArrpzsnARBeJMEWhJVNKRQXvi44WsXRBZmCTb9ulGzLo2LAtWtbZC7/ugHAJJF4bFa/2zOzgNfUHiWlv/URGSGqRdmx9gdsD8A2vx/mk9oCErkk3QPSMW7R18c480/FXFGiM9TDYWswwf4SQV55rULbSDzLY1zxDtInpMOqbXdczdKUdMpfuh8Ah1ANygO8h2mJD7M1WGSz3Mi39sCkwqiwCDgIbmTpM7E1WdIxeqSy1QrOiL6JN7d4Z9ROhZabeA2RSWchkUoIkqsbvzV1nwh3+yf5/X+slNHN5+W5/rWEAafMCzn/2odevmnrsKNX6AIV5dZJQyXirGKCKitv2oEJa7lGGd5a6r04NbaWF5MqzUuZ/8fEARQY0JER/9pCg/LE0xpTFCdsKKpTsXU5phnUN+R2v5ebxCxkKpGQbGGakNoTh14c6YSbaoveL5QOBZ1n3yMDdLxCIskGMN5eoUosbwSla8qtCPlC/m+joHqoRFOgr5PlO5zUqwFaaoCSkHzsZ2FdXuyg2ZVLKuYSppBUbftfEXckE4eF9rgTpdkKNx8W3jQatIY=

notifications:
  email:
  - julienboz@gmail.com
